edges:
  smooth:
    enabled: true
    type: cubicBezier
    roundness: 0.5
  arrows:
    to:
      enabled: true
      scaleFactor: 0.5

nodes:
  shape: box
  font:
    size: 14
    face: monospace

layout:
  hierarchical:
    enabled: true
    direction: LR
    sortMethod: directed
    nodeSpacing: 50
    levelSeparation: 250
    treeSpacing: 100
    blockShifting: false
    edgeMinimization: false
    parentCentralization: false
    shakeTowards: roots

interaction:
  hover: true
  navigationButtons: true
  keyboard: true
  zoomView: true
  dragView: true

physics:
  enabled: false

groups:
  import:
    color:
      background: "#BA68C8"
      border: "#8E24AA"

  definition:
    color:
      background: "#42A5F5"
      border: "#1E88E5"

  control_flow:
    color:
      background: "#FFA726"
      border: "#F57C00"

  operator:
    color:
      background: "#66BB6A"
      border: "#43A047"

  name:
    color:
      background: "#26C6DA"
      border: "#00ACC1"

  assignment:
    color:
      background: "#FFCA28"
      border: "#FFA000"

  call:
    color:
      background: "#9575CD"
      border: "#7E57C2"

  data_structure:
    color:
      background: "#29B6F6"
      border: "#039BE5"

  control_transfer:
    color:
      background: "#EC407A"
      border: "#D81B60"

  expression:
    color:
      background: "#BDBDBD"
      border: "#757575"

  metadata:
    color:
      background: "#78909C"
      border: "#546E7A"

  declaration:
    color:
      background: "#A1887F"
      border: "#6D4C41"

  statement:
    color:
      background: "#BDBDBD"
      border: "#757575"

  local:
    color:
      background: "#90CAF9"
      border: "#42A5F5"
      highlight:
        background: "#BBDEFB"
        border: "#2196F3"

  stdlib:
    color:
      background: "#FFF59D"
      border: "#FBC02D"
      highlight:
        background: "#FFFF8D"
        border: "#F9A825"

  external:
    color:
      background: "#FFCC80"
      border: "#FB8C00"
      highlight:
        background: "#FFE0B2"
        border: "#F57C00"

  unavailable:
    color:
      background: "#EF9A9A"
      border: "#E53935"
      highlight:
        background: "#FFCDD2"
        border: "#D32F2F"

  ".":
    color:
      background: "#BCAAA4"
      border: "#8D6E63"
      highlight:
        background: "#D7CCC8"
        border: "#6D4C41"
