edges:
  smooth:
    enabled: true
    type: cubicBezier
    roundness: 0.5
  arrows:
    to:
      enabled: true
      scaleFactor: 0.5

nodes:
  shape: box
  font:
    size: 14
    face: monospace

layout:
  hierarchical:
    enabled: true
    direction: LR
    sortMethod: directed
    nodeSpacing: 50
    levelSeparation: 250
    treeSpacing: 100
    blockShifting: false
    edgeMinimization: false
    parentCentralization: false
    shakeTowards: roots

interaction:
  hover: true
  navigationButtons: true
  keyboard: true
  zoomView: true
  dragView: true

physics:
  enabled: false

groups:
  import:
    color:
      background: ${ast_groups.import.background}
      border: ${ast_groups.import.border}

  definition:
    color:
      background: ${ast_groups.definition.background}
      border: ${ast_groups.definition.border}

  control_flow:
    color:
      background: ${ast_groups.control_flow.background}
      border: ${ast_groups.control_flow.border}

  operator:
    color:
      background: ${ast_groups.operator.background}
      border: ${ast_groups.operator.border}

  name:
    color:
      background: ${ast_groups.name.background}
      border: ${ast_groups.name.border}

  assignment:
    color:
      background: ${ast_groups.assignment.background}
      border: ${ast_groups.assignment.border}

  call:
    color:
      background: ${ast_groups.call.background}
      border: ${ast_groups.call.border}

  data_structure:
    color:
      background: ${ast_groups.data_structure.background}
      border: ${ast_groups.data_structure.border}

  control_transfer:
    color:
      background: ${ast_groups.control_transfer.background}
      border: ${ast_groups.control_transfer.border}

  expression:
    color:
      background: ${ast_groups.expression.background}
      border: ${ast_groups.expression.border}

  metadata:
    color:
      background: ${ast_groups.metadata.background}
      border: ${ast_groups.metadata.border}

  declaration:
    color:
      background: ${ast_groups.declaration.background}
      border: ${ast_groups.declaration.border}

  statement:
    color:
      background: ${ast_groups.statement.background}
      border: ${ast_groups.statement.border}

  local:
    color:
      background: ${module_groups.local.background}
      border: ${module_groups.local.border}
      highlight:
        background: ${module_groups.local.highlight.background}
        border: ${module_groups.local.highlight.border}

  stdlib:
    color:
      background: ${module_groups.stdlib.background}
      border: ${module_groups.stdlib.border}
      highlight:
        background: ${module_groups.stdlib.highlight.background}
        border: ${module_groups.stdlib.highlight.border}

  external:
    color:
      background: ${module_groups.external.background}
      border: ${module_groups.external.border}
      highlight:
        background: ${module_groups.external.highlight.background}
        border: ${module_groups.external.highlight.border}

  unavailable:
    color:
      background: ${module_groups.unavailable.background}
      border: ${module_groups.unavailable.border}
      highlight:
        background: ${module_groups.unavailable.highlight.background}
        border: ${module_groups.unavailable.highlight.border}

  ".":
    color:
      background: ${path_groups.directory.background}
      border: ${path_groups.directory.border}
      highlight:
        background: ${path_groups.directory.highlight.background}
        border: ${path_groups.directory.highlight.border}
