background_color: "#202020"
font_color: "#000000"

node:
  font:
    color: "#000000"
    size: 14

edge:
  color: "#848484"
  highlight_color: "#AAAAAA"
  hover_color: "#999999"
  font:
    color: "#000000"
    size: 12

ast_groups:
  import:
    background: "#A98CB5"
    border: "#8B6FA2"

  definition:
    background: "#8FA9C8"
    border: "#728CAB"

  control_flow:
    background: "#C9A87A"
    border: "#AC8B5D"

  operator:
    background: "#94B894"
    border: "#779B77"

  name:
    background: "#7AB8C8"
    border: "#5D9BAB"

  assignment:
    background: "#C9B87A"
    border: "#AC9B5D"

  call:
    background: "#A895C8"
    border: "#8B78AB"

  data_structure:
    background: "#7AA8C8"
    border: "#5D8BAB"

  control_transfer:
    background: "#C87A94"
    border: "#AB5D77"

  expression:
    background: "#A8A8A8"
    border: "#8B8B8B"

  metadata:
    background: "#8B9BA8"
    border: "#6E7E8B"

  declaration:
    background: "#B89F94"
    border: "#9B8277"

  statement:
    background: "#A8A8A8"
    border: "#8B8B8B"

module_groups:
  local:
    background: "#8FA9C8"
    border: "#728CAB"
    highlight:
      background: "#A4BED7"
      border: "#87A1BA"

  stdlib:
    background: "#C9B87A"
    border: "#AC9B5D"
    highlight:
      background: "#D8C78F"
      border: "#BBB072"

  external:
    background: "#C9A87A"
    border: "#AC8B5D"
    highlight:
      background: "#D8BD8F"
      border: "#BBA072"

  unavailable:
    background: "#C87A7A"
    border: "#AB5D5D"
    highlight:
      background: "#D78F8F"
      border: "#BA7272"

path_groups:
  directory:
    background: "#B89F94"
    border: "#9B8277"
    highlight:
      background: "#C7B4A9"
      border: "#AA978C"
